baseURL = 'https://rvenie.pro/'
languageCode = 'en-us'
title = 'Привет!'
theme = 'hugo-blog-awesome'


[[params.socialIcons]]
name = "github"
url = "https://github.com/rvenie"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/rvenie"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
